### ISSUE TITLE
maven工程下，自定义词典路径

### ISSUE THREAD

**Issue by jiacanli** [NLPchina/ansj_seg#599]
想问下Maven web工程下，自定义的词典文件应该放在哪里，我试了放在工程根目录和resources文件夹下都不行，还有就是自定义继承Path2Stream的类怎么才能起作用

**Comment by ansjsun** [comment]
第一种方法 在classpath下面放个ansj_library.properties 里面定义

第二种方法 在project根目录library目录里放词典。自定义词典名称叫default.dic参考https://github.com/NLPchina/ansj_seg/tree/master/library

**Comment by liweizhuo001** [comment]
能否写一个测试代码？之前基于UserDefineLibrary的方法貌似不能用了。

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/library/DicLibraryTest.java这里https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/splitWord/analysis/DicAnalysisTest.javaOn 22 Dec 2017, at 5:52 PM, Weizhuo Li <notifications@github.com> wrote:能否写一个测试代码？之前基于UserDefineLibrary的方法貌似不能用了。—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/library/DicLibraryTest.java <https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/library/DicLibraryTest.java>

这里

https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/splitWord/analysis/DicAnalysisTest.java <https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/splitWord/analysis/DicAnalysisTest.java>

**Comment by liweizhuo001** [comment]
看到了，谢谢。另外，我用 Forest forest = Library.makeForest("library/default.dic");  MyStaticValue.putLibrary("library/default.dic",forest);  后面这句的函数是不是在5.1.2的版本里没有呀。是不是最近的版本里增加的？如果不执行后面这句，貌似用户字典是不会直接起作用的。

**Comment by ansjsun** [comment]
类名称换了。可以参见wiki
